/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SpeechServicesApiVersion20241115);
  }
}(this, function(expect, SpeechServicesApiVersion20241115) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DatasetLinks', function() {
      beforeEach(function() {
        instance = new SpeechServicesApiVersion20241115.DatasetLinks();
      });

      it('should create an instance of DatasetLinks', function() {
        // TODO: update the code to test DatasetLinks
        expect(instance).to.be.a(SpeechServicesApiVersion20241115.DatasetLinks);
      });

      it('should have the property files (base name: "files")', function() {
        // TODO: update the code to test the property files
        expect(instance).to.have.property('files');
        // expect(instance.files).to.be(expectedValueLiteral);
      });

      it('should have the property commitBlocks (base name: "commitBlocks")', function() {
        // TODO: update the code to test the property commitBlocks
        expect(instance).to.have.property('commitBlocks');
        // expect(instance.commitBlocks).to.be(expectedValueLiteral);
      });

      it('should have the property listBlocks (base name: "listBlocks")', function() {
        // TODO: update the code to test the property listBlocks
        expect(instance).to.have.property('listBlocks');
        // expect(instance.listBlocks).to.be(expectedValueLiteral);
      });

      it('should have the property uploadBlocks (base name: "uploadBlocks")', function() {
        // TODO: update the code to test the property uploadBlocks
        expect(instance).to.have.property('uploadBlocks');
        // expect(instance.uploadBlocks).to.be(expectedValueLiteral);
      });

    });
  });

}));
