/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SpeechServicesApiVersion20241115);
  }
}(this, function(expect, SpeechServicesApiVersion20241115) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DatasetKind', function() {
      beforeEach(function() {
        instance = SpeechServicesApiVersion20241115.DatasetKind;
      });

      it('should create an instance of DatasetKind', function() {
        // TODO: update the code to test DatasetKind
        expect(instance).to.be.a('object');
      });

      it('should have the property language', function() {
        expect(instance).to.have.property('language');
        expect(instance.language).to.be("Language");
      });

      it('should have the property acoustic', function() {
        expect(instance).to.have.property('acoustic');
        expect(instance.acoustic).to.be("Acoustic");
      });

      it('should have the property pronunciation', function() {
        expect(instance).to.have.property('pronunciation');
        expect(instance.pronunciation).to.be("Pronunciation");
      });

      it('should have the property audioFiles', function() {
        expect(instance).to.have.property('audioFiles');
        expect(instance.audioFiles).to.be("AudioFiles");
      });

      it('should have the property languageMarkdown', function() {
        expect(instance).to.have.property('languageMarkdown');
        expect(instance.languageMarkdown).to.be("LanguageMarkdown");
      });

      it('should have the property outputFormatting', function() {
        expect(instance).to.have.property('outputFormatting');
        expect(instance.outputFormatting).to.be("OutputFormatting");
      });

    });
  });

}));
