/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SpeechServicesApiVersion20241115);
  }
}(this, function(expect, SpeechServicesApiVersion20241115) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('FileKind', function() {
      beforeEach(function() {
        instance = SpeechServicesApiVersion20241115.FileKind;
      });

      it('should create an instance of FileKind', function() {
        // TODO: update the code to test FileKind
        expect(instance).to.be.a('object');
      });

      it('should have the property datasetReport', function() {
        expect(instance).to.have.property('datasetReport');
        expect(instance.datasetReport).to.be("DatasetReport");
      });

      it('should have the property audio', function() {
        expect(instance).to.have.property('audio');
        expect(instance.audio).to.be("Audio");
      });

      it('should have the property languageData', function() {
        expect(instance).to.have.property('languageData');
        expect(instance.languageData).to.be("LanguageData");
      });

      it('should have the property pronunciationData', function() {
        expect(instance).to.have.property('pronunciationData');
        expect(instance.pronunciationData).to.be("PronunciationData");
      });

      it('should have the property acousticDataArchive', function() {
        expect(instance).to.have.property('acousticDataArchive');
        expect(instance.acousticDataArchive).to.be("AcousticDataArchive");
      });

      it('should have the property acousticDataTranscriptionV2', function() {
        expect(instance).to.have.property('acousticDataTranscriptionV2');
        expect(instance.acousticDataTranscriptionV2).to.be("AcousticDataTranscriptionV2");
      });

      it('should have the property transcription', function() {
        expect(instance).to.have.property('transcription');
        expect(instance.transcription).to.be("Transcription");
      });

      it('should have the property transcriptionReport', function() {
        expect(instance).to.have.property('transcriptionReport');
        expect(instance.transcriptionReport).to.be("TranscriptionReport");
      });

      it('should have the property evaluationDetails', function() {
        expect(instance).to.have.property('evaluationDetails');
        expect(instance.evaluationDetails).to.be("EvaluationDetails");
      });

      it('should have the property modelReport', function() {
        expect(instance).to.have.property('modelReport');
        expect(instance.modelReport).to.be("ModelReport");
      });

      it('should have the property outputFormattingData', function() {
        expect(instance).to.have.property('outputFormattingData');
        expect(instance.outputFormattingData).to.be("OutputFormattingData");
      });

    });
  });

}));
