/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SpeechServicesApiVersion20241115);
  }
}(this, function(expect, SpeechServicesApiVersion20241115) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('LanguageIdentificationProperties', function() {
      beforeEach(function() {
        instance = new SpeechServicesApiVersion20241115.LanguageIdentificationProperties();
      });

      it('should create an instance of LanguageIdentificationProperties', function() {
        // TODO: update the code to test LanguageIdentificationProperties
        expect(instance).to.be.a(SpeechServicesApiVersion20241115.LanguageIdentificationProperties);
      });

      it('should have the property candidateLocales (base name: "candidateLocales")', function() {
        // TODO: update the code to test the property candidateLocales
        expect(instance).to.have.property('candidateLocales');
        // expect(instance.candidateLocales).to.be(expectedValueLiteral);
      });

      it('should have the property speechModelMapping (base name: "speechModelMapping")', function() {
        // TODO: update the code to test the property speechModelMapping
        expect(instance).to.have.property('speechModelMapping');
        // expect(instance.speechModelMapping).to.be(expectedValueLiteral);
      });

      it('should have the property mode (base name: "mode")', function() {
        // TODO: update the code to test the property mode
        expect(instance).to.have.property('mode');
        // expect(instance.mode).to.be(expectedValueLiteral);
      });

    });
  });

}));
