/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SpeechServicesApiVersion20241115);
  }
}(this, function(expect, SpeechServicesApiVersion20241115) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('LanguageIdentificationMode', function() {
      beforeEach(function() {
        instance = SpeechServicesApiVersion20241115.LanguageIdentificationMode;
      });

      it('should create an instance of LanguageIdentificationMode', function() {
        // TODO: update the code to test LanguageIdentificationMode
        expect(instance).to.be.a('object');
      });

      it('should have the property continuous', function() {
        expect(instance).to.have.property('continuous');
        expect(instance.continuous).to.be("Continuous");
      });

      it('should have the property single', function() {
        expect(instance).to.have.property('single');
        expect(instance.single).to.be("Single");
      });

    });
  });

}));
