/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SpeechServicesApiVersion20241115);
  }
}(this, function(expect, SpeechServicesApiVersion20241115) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Phrase', function() {
      beforeEach(function() {
        instance = new SpeechServicesApiVersion20241115.Phrase();
      });

      it('should create an instance of Phrase', function() {
        // TODO: update the code to test Phrase
        expect(instance).to.be.a(SpeechServicesApiVersion20241115.Phrase);
      });

      it('should have the property channel (base name: "channel")', function() {
        // TODO: update the code to test the property channel
        expect(instance).to.have.property('channel');
        // expect(instance.channel).to.be(expectedValueLiteral);
      });

      it('should have the property speaker (base name: "speaker")', function() {
        // TODO: update the code to test the property speaker
        expect(instance).to.have.property('speaker');
        // expect(instance.speaker).to.be(expectedValueLiteral);
      });

      it('should have the property offsetMilliseconds (base name: "offsetMilliseconds")', function() {
        // TODO: update the code to test the property offsetMilliseconds
        expect(instance).to.have.property('offsetMilliseconds');
        // expect(instance.offsetMilliseconds).to.be(expectedValueLiteral);
      });

      it('should have the property durationMilliseconds (base name: "durationMilliseconds")', function() {
        // TODO: update the code to test the property durationMilliseconds
        expect(instance).to.have.property('durationMilliseconds');
        // expect(instance.durationMilliseconds).to.be(expectedValueLiteral);
      });

      it('should have the property text (base name: "text")', function() {
        // TODO: update the code to test the property text
        expect(instance).to.have.property('text');
        // expect(instance.text).to.be(expectedValueLiteral);
      });

      it('should have the property words (base name: "words")', function() {
        // TODO: update the code to test the property words
        expect(instance).to.have.property('words');
        // expect(instance.words).to.be(expectedValueLiteral);
      });

      it('should have the property locale (base name: "locale")', function() {
        // TODO: update the code to test the property locale
        expect(instance).to.have.property('locale');
        // expect(instance.locale).to.be(expectedValueLiteral);
      });

      it('should have the property confidence (base name: "confidence")', function() {
        // TODO: update the code to test the property confidence
        expect(instance).to.have.property('confidence');
        // expect(instance.confidence).to.be(expectedValueLiteral);
      });

    });
  });

}));
