/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SpeechServicesApiVersion20241115);
  }
}(this, function(expect, SpeechServicesApiVersion20241115) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SharedModelFeatures', function() {
      beforeEach(function() {
        instance = new SpeechServicesApiVersion20241115.SharedModelFeatures();
      });

      it('should create an instance of SharedModelFeatures', function() {
        // TODO: update the code to test SharedModelFeatures
        expect(instance).to.be.a(SpeechServicesApiVersion20241115.SharedModelFeatures);
      });

      it('should have the property supportsTranscriptionsSubmit (base name: "supportsTranscriptionsSubmit")', function() {
        // TODO: update the code to test the property supportsTranscriptionsSubmit
        expect(instance).to.have.property('supportsTranscriptionsSubmit');
        // expect(instance.supportsTranscriptionsSubmit).to.be(expectedValueLiteral);
      });

      it('should have the property supportsTranscriptionsTranscribe (base name: "supportsTranscriptionsTranscribe")', function() {
        // TODO: update the code to test the property supportsTranscriptionsTranscribe
        expect(instance).to.have.property('supportsTranscriptionsTranscribe');
        // expect(instance.supportsTranscriptionsTranscribe).to.be(expectedValueLiteral);
      });

      it('should have the property supportsEndpoints (base name: "supportsEndpoints")', function() {
        // TODO: update the code to test the property supportsEndpoints
        expect(instance).to.have.property('supportsEndpoints');
        // expect(instance.supportsEndpoints).to.be(expectedValueLiteral);
      });

      it('should have the property supportsTranscriptionsOnSpeechContainers (base name: "supportsTranscriptionsOnSpeechContainers")', function() {
        // TODO: update the code to test the property supportsTranscriptionsOnSpeechContainers
        expect(instance).to.have.property('supportsTranscriptionsOnSpeechContainers');
        // expect(instance.supportsTranscriptionsOnSpeechContainers).to.be(expectedValueLiteral);
      });

      it('should have the property supportedOutputFormats (base name: "supportedOutputFormats")', function() {
        // TODO: update the code to test the property supportedOutputFormats
        expect(instance).to.have.property('supportedOutputFormats');
        // expect(instance.supportedOutputFormats).to.be(expectedValueLiteral);
      });

    });
  });

}));
