/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SpeechServicesApiVersion20241115);
  }
}(this, function(expect, SpeechServicesApiVersion20241115) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TranscribeDefinition', function() {
      beforeEach(function() {
        instance = new SpeechServicesApiVersion20241115.TranscribeDefinition();
      });

      it('should create an instance of TranscribeDefinition', function() {
        // TODO: update the code to test TranscribeDefinition
        expect(instance).to.be.a(SpeechServicesApiVersion20241115.TranscribeDefinition);
      });

      it('should have the property locales (base name: "locales")', function() {
        // TODO: update the code to test the property locales
        expect(instance).to.have.property('locales');
        // expect(instance.locales).to.be(expectedValueLiteral);
      });

      it('should have the property models (base name: "models")', function() {
        // TODO: update the code to test the property models
        expect(instance).to.have.property('models');
        // expect(instance.models).to.be(expectedValueLiteral);
      });

      it('should have the property profanityFilterMode (base name: "profanityFilterMode")', function() {
        // TODO: update the code to test the property profanityFilterMode
        expect(instance).to.have.property('profanityFilterMode');
        // expect(instance.profanityFilterMode).to.be(expectedValueLiteral);
      });

      it('should have the property diarization (base name: "diarization")', function() {
        // TODO: update the code to test the property diarization
        expect(instance).to.have.property('diarization');
        // expect(instance.diarization).to.be(expectedValueLiteral);
      });

      it('should have the property channels (base name: "channels")', function() {
        // TODO: update the code to test the property channels
        expect(instance).to.have.property('channels');
        // expect(instance.channels).to.be(expectedValueLiteral);
      });

    });
  });

}));
