/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SpeechServicesApiVersion20241115);
  }
}(this, function(expect, SpeechServicesApiVersion20241115) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TranscriptionProperties', function() {
      beforeEach(function() {
        instance = new SpeechServicesApiVersion20241115.TranscriptionProperties();
      });

      it('should create an instance of TranscriptionProperties', function() {
        // TODO: update the code to test TranscriptionProperties
        expect(instance).to.be.a(SpeechServicesApiVersion20241115.TranscriptionProperties);
      });

      it('should have the property wordLevelTimestampsEnabled (base name: "wordLevelTimestampsEnabled")', function() {
        // TODO: update the code to test the property wordLevelTimestampsEnabled
        expect(instance).to.have.property('wordLevelTimestampsEnabled');
        // expect(instance.wordLevelTimestampsEnabled).to.be(expectedValueLiteral);
      });

      it('should have the property displayFormWordLevelTimestampsEnabled (base name: "displayFormWordLevelTimestampsEnabled")', function() {
        // TODO: update the code to test the property displayFormWordLevelTimestampsEnabled
        expect(instance).to.have.property('displayFormWordLevelTimestampsEnabled');
        // expect(instance.displayFormWordLevelTimestampsEnabled).to.be(expectedValueLiteral);
      });

      it('should have the property channels (base name: "channels")', function() {
        // TODO: update the code to test the property channels
        expect(instance).to.have.property('channels');
        // expect(instance.channels).to.be(expectedValueLiteral);
      });

      it('should have the property punctuationMode (base name: "punctuationMode")', function() {
        // TODO: update the code to test the property punctuationMode
        expect(instance).to.have.property('punctuationMode');
        // expect(instance.punctuationMode).to.be(expectedValueLiteral);
      });

      it('should have the property profanityFilterMode (base name: "profanityFilterMode")', function() {
        // TODO: update the code to test the property profanityFilterMode
        expect(instance).to.have.property('profanityFilterMode');
        // expect(instance.profanityFilterMode).to.be(expectedValueLiteral);
      });

      it('should have the property destinationContainerUrl (base name: "destinationContainerUrl")', function() {
        // TODO: update the code to test the property destinationContainerUrl
        expect(instance).to.have.property('destinationContainerUrl');
        // expect(instance.destinationContainerUrl).to.be(expectedValueLiteral);
      });

      it('should have the property timeToLiveHours (base name: "timeToLiveHours")', function() {
        // TODO: update the code to test the property timeToLiveHours
        expect(instance).to.have.property('timeToLiveHours');
        // expect(instance.timeToLiveHours).to.be(expectedValueLiteral);
      });

      it('should have the property languageIdentification (base name: "languageIdentification")', function() {
        // TODO: update the code to test the property languageIdentification
        expect(instance).to.have.property('languageIdentification');
        // expect(instance.languageIdentification).to.be(expectedValueLiteral);
      });

      it('should have the property diarization (base name: "diarization")', function() {
        // TODO: update the code to test the property diarization
        expect(instance).to.have.property('diarization');
        // expect(instance.diarization).to.be(expectedValueLiteral);
      });

      it('should have the property error (base name: "error")', function() {
        // TODO: update the code to test the property error
        expect(instance).to.have.property('error');
        // expect(instance.error).to.be(expectedValueLiteral);
      });

      it('should have the property durationMilliseconds (base name: "durationMilliseconds")', function() {
        // TODO: update the code to test the property durationMilliseconds
        expect(instance).to.have.property('durationMilliseconds');
        // expect(instance.durationMilliseconds).to.be(expectedValueLiteral);
      });

    });
  });

}));
