/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CustomModelDeprecationDates', 'model/CustomModelFeatures', 'model/EntityError'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CustomModelDeprecationDates'), require('./CustomModelFeatures'), require('./EntityError'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.CustomModelProperties = factory(root.SpeechServicesApiVersion20241115.ApiClient, root.SpeechServicesApiVersion20241115.CustomModelDeprecationDates, root.SpeechServicesApiVersion20241115.CustomModelFeatures, root.SpeechServicesApiVersion20241115.EntityError);
  }
}(this, function(ApiClient, CustomModelDeprecationDates, CustomModelFeatures, EntityError) {
  'use strict';

  /**
   * The CustomModelProperties model module.
   * @module model/CustomModelProperties
   * @version 2024-11-15
   */

  /**
   * Constructs a new <code>CustomModelProperties</code>.
   * @alias module:model/CustomModelProperties
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>CustomModelProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomModelProperties} obj Optional instance to populate.
   * @return {module:model/CustomModelProperties} The populated <code>CustomModelProperties</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('deprecationDates'))
        obj.deprecationDates = CustomModelDeprecationDates.constructFromObject(data['deprecationDates']);
      if (data.hasOwnProperty('customModelWeightPercent'))
        obj.customModelWeightPercent = ApiClient.convertToType(data['customModelWeightPercent'], 'Number');
      if (data.hasOwnProperty('features'))
        obj.features = CustomModelFeatures.constructFromObject(data['features']);
      if (data.hasOwnProperty('error'))
        obj.error = EntityError.constructFromObject(data['error']);
    }
    return obj;
  }

  /**
   * @member {module:model/CustomModelDeprecationDates} deprecationDates
   */
  exports.prototype.deprecationDates = undefined;

  /**
   * The weight of custom model between 1 (1% custom model and 99% base model) and 100 (100% custom model and 0% base model). When this property is not set, the service chooses a suitable value (get the model to retrieve the selected weight). Start without using this property. If needed, choose a larger (or smaller) weight to increase (or decrease) the impact of the custom model.
   * @member {Number} customModelWeightPercent
   */
  exports.prototype.customModelWeightPercent = undefined;

  /**
   * @member {module:model/CustomModelFeatures} features
   */
  exports.prototype.features = undefined;

  /**
   * @member {module:model/EntityError} error
   */
  exports.prototype.error = undefined;


  return exports;

}));
