/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.DatasetLinks = factory(root.SpeechServicesApiVersion20241115.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The DatasetLinks model module.
   * @module model/DatasetLinks
   * @version 2024-11-15
   */

  /**
   * Constructs a new <code>DatasetLinks</code>.
   * @alias module:model/DatasetLinks
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DatasetLinks</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DatasetLinks} obj Optional instance to populate.
   * @return {module:model/DatasetLinks} The populated <code>DatasetLinks</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('files'))
        obj.files = ApiClient.convertToType(data['files'], 'String');
      if (data.hasOwnProperty('commitBlocks'))
        obj.commitBlocks = ApiClient.convertToType(data['commitBlocks'], 'String');
      if (data.hasOwnProperty('listBlocks'))
        obj.listBlocks = ApiClient.convertToType(data['listBlocks'], 'String');
      if (data.hasOwnProperty('uploadBlocks'))
        obj.uploadBlocks = ApiClient.convertToType(data['uploadBlocks'], 'String');
    }
    return obj;
  }

  /**
   * The location to get all files of this entity. See operation \"Datasets_ListFiles\" for more details.
   * @member {String} files
   */
  exports.prototype.files = undefined;

  /**
   * The location to commit the list of blocks when uploading a dataset using blocks. See operation \"Datasets_CommitBlocks\" for more details.
   * @member {String} commitBlocks
   */
  exports.prototype.commitBlocks = undefined;

  /**
   * The location to list the already uploaded blocks of this entity when uploading a dataset using blocks. See operation \"Datasets_GetBlocks\" for more details.
   * @member {String} listBlocks
   */
  exports.prototype.listBlocks = undefined;

  /**
   * The location to upload blocks to when uploading a dataset using blocks. See operation \"Datasets_UploadBlock\" for more details.
   * @member {String} uploadBlocks
   */
  exports.prototype.uploadBlocks = undefined;


  return exports;

}));
