/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EntityError', 'model/TextNormalizationKind'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EntityError'), require('./TextNormalizationKind'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.DatasetProperties = factory(root.SpeechServicesApiVersion20241115.ApiClient, root.SpeechServicesApiVersion20241115.EntityError, root.SpeechServicesApiVersion20241115.TextNormalizationKind);
  }
}(this, function(ApiClient, EntityError, TextNormalizationKind) {
  'use strict';

  /**
   * The DatasetProperties model module.
   * @module model/DatasetProperties
   * @version 2024-11-15
   */

  /**
   * Constructs a new <code>DatasetProperties</code>.
   * @alias module:model/DatasetProperties
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DatasetProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DatasetProperties} obj Optional instance to populate.
   * @return {module:model/DatasetProperties} The populated <code>DatasetProperties</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('acceptedLineCount'))
        obj.acceptedLineCount = ApiClient.convertToType(data['acceptedLineCount'], 'Number');
      if (data.hasOwnProperty('rejectedLineCount'))
        obj.rejectedLineCount = ApiClient.convertToType(data['rejectedLineCount'], 'Number');
      if (data.hasOwnProperty('durationMilliseconds'))
        obj.durationMilliseconds = ApiClient.convertToType(data['durationMilliseconds'], 'Number');
      if (data.hasOwnProperty('textNormalizationKind'))
        obj.textNormalizationKind = TextNormalizationKind.constructFromObject(data['textNormalizationKind']);
      if (data.hasOwnProperty('error'))
        obj.error = EntityError.constructFromObject(data['error']);
    }
    return obj;
  }

  /**
   * The number of lines accepted for this data set.
   * @member {Number} acceptedLineCount
   */
  exports.prototype.acceptedLineCount = undefined;

  /**
   * The number of lines rejected for this data set.
   * @member {Number} rejectedLineCount
   */
  exports.prototype.rejectedLineCount = undefined;

  /**
   * The total duration in milliseconds of the datasets if it contains audio files. Durations larger than 2^53-1 are not supported to ensure compatibility with JavaScript integers.
   * @member {Number} durationMilliseconds
   * @default 0
   */
  exports.prototype.durationMilliseconds = 0;

  /**
   * @member {module:model/TextNormalizationKind} textNormalizationKind
   */
  exports.prototype.textNormalizationKind = undefined;

  /**
   * @member {module:model/EntityError} error
   */
  exports.prototype.error = undefined;


  return exports;

}));
