/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.DatasetKind = factory(root.SpeechServicesApiVersion20241115.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * Enum class DatasetKind.
   * @enum {String}
   * @readonly
   */
  var exports = {
    /**
     * value: "Language"
     * @const
     */
    language: "Language",

    /**
     * value: "Acoustic"
     * @const
     */
    acoustic: "Acoustic",

    /**
     * value: "Pronunciation"
     * @const
     */
    pronunciation: "Pronunciation",

    /**
     * value: "AudioFiles"
     * @const
     */
    audioFiles: "AudioFiles",

    /**
     * value: "LanguageMarkdown"
     * @const
     */
    languageMarkdown: "LanguageMarkdown",

    /**
     * value: "OutputFormatting"
     * @const
     */
    outputFormatting: "OutputFormatting"
  };

  /**
   * Returns a <code>DatasetKind</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/DatasetKind} The enum <code>DatasetKind</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));
