/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EndpointPropertiesUpdate', 'model/EntityReference'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EndpointPropertiesUpdate'), require('./EntityReference'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.EndpointUpdate = factory(root.SpeechServicesApiVersion20241115.ApiClient, root.SpeechServicesApiVersion20241115.EndpointPropertiesUpdate, root.SpeechServicesApiVersion20241115.EntityReference);
  }
}(this, function(ApiClient, EndpointPropertiesUpdate, EntityReference) {
  'use strict';

  /**
   * The EndpointUpdate model module.
   * @module model/EndpointUpdate
   * @version 2024-11-15
   */

  /**
   * Constructs a new <code>EndpointUpdate</code>.
   * @alias module:model/EndpointUpdate
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>EndpointUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EndpointUpdate} obj Optional instance to populate.
   * @return {module:model/EndpointUpdate} The populated <code>EndpointUpdate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('model'))
        obj.model = EntityReference.constructFromObject(data['model']);
      if (data.hasOwnProperty('properties'))
        obj.properties = EndpointPropertiesUpdate.constructFromObject(data['properties']);
      if (data.hasOwnProperty('customProperties'))
        obj.customProperties = ApiClient.convertToType(data['customProperties'], {'String': 'String'});
    }
    return obj;
  }

  /**
   * The name of the object.
   * @member {String} displayName
   */
  exports.prototype.displayName = undefined;

  /**
   * The description of the object.
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {module:model/EntityReference} model
   */
  exports.prototype.model = undefined;

  /**
   * @member {module:model/EndpointPropertiesUpdate} properties
   */
  exports.prototype.properties = undefined;

  /**
   * The custom properties of this entity. The maximum allowed key length is 64 characters, the maximum allowed value length is 256 characters and the count of allowed entries is 10.
   * @member {Object.<String, String>} customProperties
   */
  exports.prototype.customProperties = undefined;


  return exports;

}));
