/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FileKind', 'model/FileLinks', 'model/FileProperties'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FileKind'), require('./FileLinks'), require('./FileProperties'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.File = factory(root.SpeechServicesApiVersion20241115.ApiClient, root.SpeechServicesApiVersion20241115.FileKind, root.SpeechServicesApiVersion20241115.FileLinks, root.SpeechServicesApiVersion20241115.FileProperties);
  }
}(this, function(ApiClient, FileKind, FileLinks, FileProperties) {
  'use strict';

  /**
   * The File model module.
   * @module model/File
   * @version 2024-11-15
   */

  /**
   * Constructs a new <code>File</code>.
   * @alias module:model/File
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>File</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/File} obj Optional instance to populate.
   * @return {module:model/File} The populated <code>File</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('self'))
        obj.self = ApiClient.convertToType(data['self'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('kind'))
        obj.kind = FileKind.constructFromObject(data['kind']);
      if (data.hasOwnProperty('links'))
        obj.links = FileLinks.constructFromObject(data['links']);
      if (data.hasOwnProperty('properties'))
        obj.properties = FileProperties.constructFromObject(data['properties']);
      if (data.hasOwnProperty('createdDateTime'))
        obj.createdDateTime = ApiClient.convertToType(data['createdDateTime'], 'Date');
    }
    return obj;
  }

  /**
   * The location of this entity.
   * @member {String} self
   */
  exports.prototype.self = undefined;

  /**
   * The name of this file.
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {module:model/FileKind} kind
   */
  exports.prototype.kind = undefined;

  /**
   * @member {module:model/FileLinks} links
   */
  exports.prototype.links = undefined;

  /**
   * @member {module:model/FileProperties} properties
   */
  exports.prototype.properties = undefined;

  /**
   * The creation time of this file. The time stamp is encoded as ISO 8601 date and time format (see https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations).
   * @member {Date} createdDateTime
   */
  exports.prototype.createdDateTime = undefined;


  return exports;

}));
