/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.TranscribeDiarizationProperties = factory(root.SpeechServicesApiVersion20241115.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The TranscribeDiarizationProperties model module.
   * @module model/TranscribeDiarizationProperties
   * @version 2024-11-15
   */

  /**
   * Constructs a new <code>TranscribeDiarizationProperties</code>.
   * The diarization settings. Diarization settings must be specified to enable diarization.
   * @alias module:model/TranscribeDiarizationProperties
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>TranscribeDiarizationProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TranscribeDiarizationProperties} obj Optional instance to populate.
   * @return {module:model/TranscribeDiarizationProperties} The populated <code>TranscribeDiarizationProperties</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('enabled'))
        obj.enabled = ApiClient.convertToType(data['enabled'], 'Boolean');
      if (data.hasOwnProperty('maxSpeakers'))
        obj.maxSpeakers = ApiClient.convertToType(data['maxSpeakers'], 'Number');
    }
    return obj;
  }

  /**
   * Gets or sets a value indicating whether speaker diarization is enabled.
   * @member {Boolean} enabled
   */
  exports.prototype.enabled = undefined;

  /**
   * Gets or sets a hint for the maximum number of speakers for diarization. Must be greater than 1 and less than 36.
   * @member {Number} maxSpeakers
   */
  exports.prototype.maxSpeakers = undefined;


  return exports;

}));
