/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ResponseBlock'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ResponseBlock'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.UploadedBlocks = factory(root.SpeechServicesApiVersion20241115.ApiClient, root.SpeechServicesApiVersion20241115.ResponseBlock);
  }
}(this, function(ApiClient, ResponseBlock) {
  'use strict';

  /**
   * The UploadedBlocks model module.
   * @module model/UploadedBlocks
   * @version 2024-11-15
   */

  /**
   * Constructs a new <code>UploadedBlocks</code>.
   * List of uploaded blocks.
   * @alias module:model/UploadedBlocks
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>UploadedBlocks</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UploadedBlocks} obj Optional instance to populate.
   * @return {module:model/UploadedBlocks} The populated <code>UploadedBlocks</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('committedBlocks'))
        obj.committedBlocks = ApiClient.convertToType(data['committedBlocks'], [ResponseBlock]);
      if (data.hasOwnProperty('uncommittedBlocks'))
        obj.uncommittedBlocks = ApiClient.convertToType(data['uncommittedBlocks'], [ResponseBlock]);
    }
    return obj;
  }

  /**
   * The block description of blocks already committed.
   * @member {Array.<module:model/ResponseBlock>} committedBlocks
   */
  exports.prototype.committedBlocks = undefined;

  /**
   * The block description of blocks not committed to the blob.
   * @member {Array.<module:model/ResponseBlock>} uncommittedBlocks
   */
  exports.prototype.uncommittedBlocks = undefined;


  return exports;

}));
