/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.Word = factory(root.SpeechServicesApiVersion20241115.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Word model module.
   * @module model/Word
   * @version 2024-11-15
   */

  /**
   * Constructs a new <code>Word</code>.
   * Time-stamped word in the display form.
   * @alias module:model/Word
   * @class
   * @param text {String} The recognized word, including punctuation.
   * @param offsetMilliseconds {Number} The start offset of the word in milliseconds.
   * @param durationMilliseconds {Number} The duration of the word in milliseconds.
   */
  var exports = function(text, offsetMilliseconds, durationMilliseconds) {
    this.text = text;
    this.offsetMilliseconds = offsetMilliseconds;
    this.durationMilliseconds = durationMilliseconds;
  };

  /**
   * Constructs a <code>Word</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Word} obj Optional instance to populate.
   * @return {module:model/Word} The populated <code>Word</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
      if (data.hasOwnProperty('offsetMilliseconds'))
        obj.offsetMilliseconds = ApiClient.convertToType(data['offsetMilliseconds'], 'Number');
      if (data.hasOwnProperty('durationMilliseconds'))
        obj.durationMilliseconds = ApiClient.convertToType(data['durationMilliseconds'], 'Number');
    }
    return obj;
  }

  /**
   * The recognized word, including punctuation.
   * @member {String} text
   */
  exports.prototype.text = undefined;

  /**
   * The start offset of the word in milliseconds.
   * @member {Number} offsetMilliseconds
   */
  exports.prototype.offsetMilliseconds = undefined;

  /**
   * The duration of the word in milliseconds.
   * @member {Number} durationMilliseconds
   */
  exports.prototype.durationMilliseconds = undefined;


  return exports;

}));
