/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BaseModelDeprecationDates', 'model/BaseModelFeatures'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BaseModelDeprecationDates'), require('./BaseModelFeatures'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.BaseModelProperties = factory(root.SpeechServicesApiVersion20241115.ApiClient, root.SpeechServicesApiVersion20241115.BaseModelDeprecationDates, root.SpeechServicesApiVersion20241115.BaseModelFeatures);
  }
}(this, function(ApiClient, BaseModelDeprecationDates, BaseModelFeatures) {
  'use strict';

  /**
   * The BaseModelProperties model module.
   * @module model/BaseModelProperties
   * @version 2024-11-15
   */

  /**
   * Constructs a new <code>BaseModelProperties</code>.
   * @alias module:model/BaseModelProperties
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>BaseModelProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BaseModelProperties} obj Optional instance to populate.
   * @return {module:model/BaseModelProperties} The populated <code>BaseModelProperties</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('deprecationDates'))
        obj.deprecationDates = BaseModelDeprecationDates.constructFromObject(data['deprecationDates']);
      if (data.hasOwnProperty('features'))
        obj.features = BaseModelFeatures.constructFromObject(data['features']);
      if (data.hasOwnProperty('chargeForAdaptation'))
        obj.chargeForAdaptation = ApiClient.convertToType(data['chargeForAdaptation'], 'Boolean');
    }
    return obj;
  }

  /**
   * @member {module:model/BaseModelDeprecationDates} deprecationDates
   */
  exports.prototype.deprecationDates = undefined;

  /**
   * @member {module:model/BaseModelFeatures} features
   */
  exports.prototype.features = undefined;

  /**
   * A value indicating whether model adaptation is charged.
   * @member {Boolean} chargeForAdaptation
   */
  exports.prototype.chargeForAdaptation = undefined;


  return exports;

}));
