/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OutputFormatType', 'model/SharedModelFeatures'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OutputFormatType'), require('./SharedModelFeatures'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.CustomModelFeatures = factory(root.SpeechServicesApiVersion20241115.ApiClient, root.SpeechServicesApiVersion20241115.OutputFormatType, root.SpeechServicesApiVersion20241115.SharedModelFeatures);
  }
}(this, function(ApiClient, OutputFormatType, SharedModelFeatures) {
  'use strict';

  /**
   * The CustomModelFeatures model module.
   * @module model/CustomModelFeatures
   * @version 2024-11-15
   */

  /**
   * Constructs a new <code>CustomModelFeatures</code>.
   * Features supported by the model.
   * @alias module:model/CustomModelFeatures
   * @class
   * @extends module:model/SharedModelFeatures
   */
  var exports = function() {
    SharedModelFeatures.call(this);
  };

  /**
   * Constructs a <code>CustomModelFeatures</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomModelFeatures} obj Optional instance to populate.
   * @return {module:model/CustomModelFeatures} The populated <code>CustomModelFeatures</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      SharedModelFeatures.constructFromObject(data, obj);
    }
    return obj;
  }

  exports.prototype = Object.create(SharedModelFeatures.prototype);
  exports.prototype.constructor = exports;

  return exports;

}));
