/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.DatasetLocales = factory(root.SpeechServicesApiVersion20241115.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The DatasetLocales model module.
   * @module model/DatasetLocales
   * @version 2024-11-15
   */

  /**
   * Constructs a new <code>DatasetLocales</code>.
   * @alias module:model/DatasetLocales
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DatasetLocales</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DatasetLocales} obj Optional instance to populate.
   * @return {module:model/DatasetLocales} The populated <code>DatasetLocales</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Language'))
        obj.language = ApiClient.convertToType(data['Language'], ['String']);
      if (data.hasOwnProperty('Acoustic'))
        obj.acoustic = ApiClient.convertToType(data['Acoustic'], ['String']);
      if (data.hasOwnProperty('Pronunciation'))
        obj.pronunciation = ApiClient.convertToType(data['Pronunciation'], ['String']);
      if (data.hasOwnProperty('AudioFiles'))
        obj.audioFiles = ApiClient.convertToType(data['AudioFiles'], ['String']);
      if (data.hasOwnProperty('LanguageMarkdown'))
        obj.languageMarkdown = ApiClient.convertToType(data['LanguageMarkdown'], ['String']);
      if (data.hasOwnProperty('OutputFormatting'))
        obj.outputFormatting = ApiClient.convertToType(data['OutputFormatting'], ['String']);
    }
    return obj;
  }

  /**
   * @member {Array.<String>} language
   */
  exports.prototype.language = undefined;

  /**
   * @member {Array.<String>} acoustic
   */
  exports.prototype.acoustic = undefined;

  /**
   * @member {Array.<String>} pronunciation
   */
  exports.prototype.pronunciation = undefined;

  /**
   * @member {Array.<String>} audioFiles
   */
  exports.prototype.audioFiles = undefined;

  /**
   * @member {Array.<String>} languageMarkdown
   */
  exports.prototype.languageMarkdown = undefined;

  /**
   * @member {Array.<String>} outputFormatting
   */
  exports.prototype.outputFormatting = undefined;


  return exports;

}));
