/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.DetailedErrorCode = factory(root.SpeechServicesApiVersion20241115.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * Enum class DetailedErrorCode.
   * @enum {String}
   * @readonly
   */
  var exports = {
    /**
     * value: "InvalidParameterValue"
     * @const
     */
    invalidParameterValue: "InvalidParameterValue",

    /**
     * value: "InvalidRequestBodyFormat"
     * @const
     */
    invalidRequestBodyFormat: "InvalidRequestBodyFormat",

    /**
     * value: "EmptyRequest"
     * @const
     */
    emptyRequest: "EmptyRequest",

    /**
     * value: "MissingInputRecords"
     * @const
     */
    missingInputRecords: "MissingInputRecords",

    /**
     * value: "InvalidDocument"
     * @const
     */
    invalidDocument: "InvalidDocument",

    /**
     * value: "ModelVersionIncorrect"
     * @const
     */
    modelVersionIncorrect: "ModelVersionIncorrect",

    /**
     * value: "InvalidDocumentBatch"
     * @const
     */
    invalidDocumentBatch: "InvalidDocumentBatch",

    /**
     * value: "UnsupportedLanguageCode"
     * @const
     */
    unsupportedLanguageCode: "UnsupportedLanguageCode",

    /**
     * value: "DataImportFailed"
     * @const
     */
    dataImportFailed: "DataImportFailed",

    /**
     * value: "InUseViolation"
     * @const
     */
    inUseViolation: "InUseViolation",

    /**
     * value: "InvalidLocale"
     * @const
     */
    invalidLocale: "InvalidLocale",

    /**
     * value: "InvalidBaseModel"
     * @const
     */
    invalidBaseModel: "InvalidBaseModel",

    /**
     * value: "InvalidAdaptationMapping"
     * @const
     */
    invalidAdaptationMapping: "InvalidAdaptationMapping",

    /**
     * value: "InvalidDataset"
     * @const
     */
    invalidDataset: "InvalidDataset",

    /**
     * value: "InvalidTest"
     * @const
     */
    invalidTest: "InvalidTest",

    /**
     * value: "FailedDataset"
     * @const
     */
    failedDataset: "FailedDataset",

    /**
     * value: "InvalidModel"
     * @const
     */
    invalidModel: "InvalidModel",

    /**
     * value: "InvalidTranscription"
     * @const
     */
    invalidTranscription: "InvalidTranscription",

    /**
     * value: "InvalidPayload"
     * @const
     */
    invalidPayload: "InvalidPayload",

    /**
     * value: "InvalidParameter"
     * @const
     */
    invalidParameter: "InvalidParameter",

    /**
     * value: "EndpointWithoutLogging"
     * @const
     */
    endpointWithoutLogging: "EndpointWithoutLogging",

    /**
     * value: "InvalidPermissions"
     * @const
     */
    invalidPermissions: "InvalidPermissions",

    /**
     * value: "InvalidPrerequisite"
     * @const
     */
    invalidPrerequisite: "InvalidPrerequisite",

    /**
     * value: "InvalidProductId"
     * @const
     */
    invalidProductId: "InvalidProductId",

    /**
     * value: "InvalidSubscription"
     * @const
     */
    invalidSubscription: "InvalidSubscription",

    /**
     * value: "InvalidProject"
     * @const
     */
    invalidProject: "InvalidProject",

    /**
     * value: "InvalidProjectKind"
     * @const
     */
    invalidProjectKind: "InvalidProjectKind",

    /**
     * value: "InvalidRecordingsUri"
     * @const
     */
    invalidRecordingsUri: "InvalidRecordingsUri",

    /**
     * value: "OnlyOneOfUrlsOrContainerOrDataset"
     * @const
     */
    onlyOneOfUrlsOrContainerOrDataset: "OnlyOneOfUrlsOrContainerOrDataset",

    /**
     * value: "ExceededNumberOfRecordingsUris"
     * @const
     */
    exceededNumberOfRecordingsUris: "ExceededNumberOfRecordingsUris",

    /**
     * value: "InvalidChannels"
     * @const
     */
    invalidChannels: "InvalidChannels",

    /**
     * value: "ModelMismatch"
     * @const
     */
    modelMismatch: "ModelMismatch",

    /**
     * value: "ProjectGenderMismatch"
     * @const
     */
    projectGenderMismatch: "ProjectGenderMismatch",

    /**
     * value: "ModelDeprecated"
     * @const
     */
    modelDeprecated: "ModelDeprecated",

    /**
     * value: "ModelExists"
     * @const
     */
    modelExists: "ModelExists",

    /**
     * value: "ModelNotDeployable"
     * @const
     */
    modelNotDeployable: "ModelNotDeployable",

    /**
     * value: "EndpointNotUpdatable"
     * @const
     */
    endpointNotUpdatable: "EndpointNotUpdatable",

    /**
     * value: "SingleDefaultEndpoint"
     * @const
     */
    singleDefaultEndpoint: "SingleDefaultEndpoint",

    /**
     * value: "EndpointCannotBeDefault"
     * @const
     */
    endpointCannotBeDefault: "EndpointCannotBeDefault",

    /**
     * value: "InvalidModelUri"
     * @const
     */
    invalidModelUri: "InvalidModelUri",

    /**
     * value: "SubscriptionNotFound"
     * @const
     */
    subscriptionNotFound: "SubscriptionNotFound",

    /**
     * value: "QuotaViolation"
     * @const
     */
    quotaViolation: "QuotaViolation",

    /**
     * value: "UnsupportedDelta"
     * @const
     */
    unsupportedDelta: "UnsupportedDelta",

    /**
     * value: "UnsupportedFilter"
     * @const
     */
    unsupportedFilter: "UnsupportedFilter",

    /**
     * value: "UnsupportedPagination"
     * @const
     */
    unsupportedPagination: "UnsupportedPagination",

    /**
     * value: "UnsupportedDynamicConfiguration"
     * @const
     */
    unsupportedDynamicConfiguration: "UnsupportedDynamicConfiguration",

    /**
     * value: "UnsupportedOrderBy"
     * @const
     */
    unsupportedOrderBy: "UnsupportedOrderBy",

    /**
     * value: "NoUtf8WithBom"
     * @const
     */
    noUtf8WithBom: "NoUtf8WithBom",

    /**
     * value: "ModelDeploymentNotCompleteState"
     * @const
     */
    modelDeploymentNotCompleteState: "ModelDeploymentNotCompleteState",

    /**
     * value: "SkuLimitsExist"
     * @const
     */
    skuLimitsExist: "SkuLimitsExist",

    /**
     * value: "DeployingFailedModel"
     * @const
     */
    deployingFailedModel: "DeployingFailedModel",

    /**
     * value: "UnsupportedTimeRange"
     * @const
     */
    unsupportedTimeRange: "UnsupportedTimeRange",

    /**
     * value: "InvalidLogDate"
     * @const
     */
    invalidLogDate: "InvalidLogDate",

    /**
     * value: "InvalidLogId"
     * @const
     */
    invalidLogId: "InvalidLogId",

    /**
     * value: "InvalidLogStartTime"
     * @const
     */
    invalidLogStartTime: "InvalidLogStartTime",

    /**
     * value: "InvalidLogEndTime"
     * @const
     */
    invalidLogEndTime: "InvalidLogEndTime",

    /**
     * value: "InvalidTopForLogs"
     * @const
     */
    invalidTopForLogs: "InvalidTopForLogs",

    /**
     * value: "InvalidSkipTokenForLogs"
     * @const
     */
    invalidSkipTokenForLogs: "InvalidSkipTokenForLogs",

    /**
     * value: "DeleteNotAllowed"
     * @const
     */
    deleteNotAllowed: "DeleteNotAllowed",

    /**
     * value: "Forbidden"
     * @const
     */
    forbidden: "Forbidden",

    /**
     * value: "DeployNotAllowed"
     * @const
     */
    deployNotAllowed: "DeployNotAllowed",

    /**
     * value: "UnexpectedError"
     * @const
     */
    unexpectedError: "UnexpectedError",

    /**
     * value: "InvalidCollection"
     * @const
     */
    invalidCollection: "InvalidCollection",

    /**
     * value: "InvalidCallbackUri"
     * @const
     */
    invalidCallbackUri: "InvalidCallbackUri",

    /**
     * value: "InvalidSasValidityDuration"
     * @const
     */
    invalidSasValidityDuration: "InvalidSasValidityDuration",

    /**
     * value: "InaccessibleCustomerStorage"
     * @const
     */
    inaccessibleCustomerStorage: "InaccessibleCustomerStorage",

    /**
     * value: "UnsupportedClassBasedAdaptation"
     * @const
     */
    unsupportedClassBasedAdaptation: "UnsupportedClassBasedAdaptation",

    /**
     * value: "InvalidWebHookEventKind"
     * @const
     */
    invalidWebHookEventKind: "InvalidWebHookEventKind",

    /**
     * value: "InvalidTimeToLive"
     * @const
     */
    invalidTimeToLive: "InvalidTimeToLive",

    /**
     * value: "InvalidSourceAzureResourceId"
     * @const
     */
    invalidSourceAzureResourceId: "InvalidSourceAzureResourceId",

    /**
     * value: "ModelCopyAuthorizationExpired"
     * @const
     */
    modelCopyAuthorizationExpired: "ModelCopyAuthorizationExpired",

    /**
     * value: "EndpointLoggingNotSupported"
     * @const
     */
    endpointLoggingNotSupported: "EndpointLoggingNotSupported",

    /**
     * value: "NoLanguageIdentified"
     * @const
     */
    noLanguageIdentified: "NoLanguageIdentified",

    /**
     * value: "MultipleLanguagesIdentified"
     * @const
     */
    multipleLanguagesIdentified: "MultipleLanguagesIdentified",

    /**
     * value: "InvalidAudioFormat"
     * @const
     */
    invalidAudioFormat: "InvalidAudioFormat",

    /**
     * value: "BadChannelConfiguration"
     * @const
     */
    badChannelConfiguration: "BadChannelConfiguration",

    /**
     * value: "InvalidChannelSpecification"
     * @const
     */
    invalidChannelSpecification: "InvalidChannelSpecification",

    /**
     * value: "AudioLengthLimitExceeded"
     * @const
     */
    audioLengthLimitExceeded: "AudioLengthLimitExceeded",

    /**
     * value: "EmptyAudioFile"
     * @const
     */
    emptyAudioFile: "EmptyAudioFile"
  };

  /**
   * Returns a <code>DetailedErrorCode</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/DetailedErrorCode} The enum <code>DetailedErrorCode</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));
