/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Error', 'model/ErrorCode', 'model/InnerError'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Error'), require('./ErrorCode'), require('./InnerError'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.Error = factory(root.SpeechServicesApiVersion20241115.ApiClient, root.SpeechServicesApiVersion20241115.Error, root.SpeechServicesApiVersion20241115.ErrorCode, root.SpeechServicesApiVersion20241115.InnerError);
  }
}(this, function(ApiClient, Error, ErrorCode, InnerError) {
  'use strict';

  /**
   * The Error model module.
   * @module model/Error
   * @version 2024-11-15
   */

  /**
   * Constructs a new <code>Error</code>.
   * This error type contains an outer error with error code, message, details, target and an inner error with more descriptive details.
   * @alias module:model/Error
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Error</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Error} obj Optional instance to populate.
   * @return {module:model/Error} The populated <code>Error</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('target'))
        obj.target = ApiClient.convertToType(data['target'], 'String');
      if (data.hasOwnProperty('innerError'))
        obj.innerError = InnerError.constructFromObject(data['innerError']);
      if (data.hasOwnProperty('code'))
        obj.code = ErrorCode.constructFromObject(data['code']);
      if (data.hasOwnProperty('details'))
        obj.details = ApiClient.convertToType(data['details'], [Error]);
    }
    return obj;
  }

  /**
   * High level error message.
   * @member {String} message
   */
  exports.prototype.message = undefined;

  /**
   * The source of the error. For example it would be \"documents\" or \"document id\" in case of invalid document.
   * @member {String} target
   */
  exports.prototype.target = undefined;

  /**
   * @member {module:model/InnerError} innerError
   */
  exports.prototype.innerError = undefined;

  /**
   * @member {module:model/ErrorCode} code
   */
  exports.prototype.code = undefined;

  /**
   * Additional supportive details regarding the error and/or expected policies.
   * @member {Array.<module:model/Error>} details
   */
  exports.prototype.details = undefined;


  return exports;

}));
