/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DetailedErrorCode', 'model/InnerError'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DetailedErrorCode'), require('./InnerError'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.InnerError = factory(root.SpeechServicesApiVersion20241115.ApiClient, root.SpeechServicesApiVersion20241115.DetailedErrorCode, root.SpeechServicesApiVersion20241115.InnerError);
  }
}(this, function(ApiClient, DetailedErrorCode, InnerError) {
  'use strict';

  /**
   * The InnerError model module.
   * @module model/InnerError
   * @version 2024-11-15
   */

  /**
   * Constructs a new <code>InnerError</code>.
   * New Inner Error format which conforms to Cognitive Services API Guidelines which is available at https://microsoft.sharepoint.com/%3Aw%3A/t/CognitiveServicesPMO/EUoytcrjuJdKpeOKIK_QRC8BPtUYQpKBi8JsWyeDMRsWlQ?e=CPq8ow. This contains required properties ErrorCode, message and optional properties target, details(key value pair), inner error(this can be nested).
   * @alias module:model/InnerError
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>InnerError</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InnerError} obj Optional instance to populate.
   * @return {module:model/InnerError} The populated <code>InnerError</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('target'))
        obj.target = ApiClient.convertToType(data['target'], 'String');
      if (data.hasOwnProperty('innerError'))
        obj.innerError = InnerError.constructFromObject(data['innerError']);
      if (data.hasOwnProperty('code'))
        obj.code = DetailedErrorCode.constructFromObject(data['code']);
      if (data.hasOwnProperty('details'))
        obj.details = ApiClient.convertToType(data['details'], {'String': 'String'});
    }
    return obj;
  }

  /**
   * High level error message.
   * @member {String} message
   */
  exports.prototype.message = undefined;

  /**
   * The source of the error. For example it would be \"documents\" or \"document id\" in case of invalid document.
   * @member {String} target
   */
  exports.prototype.target = undefined;

  /**
   * @member {module:model/InnerError} innerError
   */
  exports.prototype.innerError = undefined;

  /**
   * @member {module:model/DetailedErrorCode} code
   */
  exports.prototype.code = undefined;

  /**
   * Additional supportive details regarding the error and/or expected policies.
   * @member {Object.<String, String>} details
   */
  exports.prototype.details = undefined;


  return exports;

}));
