/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.ModelCopyAuthorization = factory(root.SpeechServicesApiVersion20241115.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ModelCopyAuthorization model module.
   * @module model/ModelCopyAuthorization
   * @version 2024-11-15
   */

  /**
   * Constructs a new <code>ModelCopyAuthorization</code>.
   * @alias module:model/ModelCopyAuthorization
   * @class
   * @param targetResourceRegion {String} The region (aka location) of the target speech resource (e.g., westus2).
   * @param targetResourceId {String} The Azure Resource ID of the target speech resource.
   * @param targetResourceEndpoint {String} The endpoint (base url) of the target resource (with custom domain name when it is used).
   * @param sourceResourceId {String} The Azure Resource ID of the source speech resource.
   * @param expirationDateTime {Date} The expiration date of this copy authorization.
   * @param id {String} The ID of this copy authorization.
   */
  var exports = function(targetResourceRegion, targetResourceId, targetResourceEndpoint, sourceResourceId, expirationDateTime, id) {
    this.targetResourceRegion = targetResourceRegion;
    this.targetResourceId = targetResourceId;
    this.targetResourceEndpoint = targetResourceEndpoint;
    this.sourceResourceId = sourceResourceId;
    this.expirationDateTime = expirationDateTime;
    this.id = id;
  };

  /**
   * Constructs a <code>ModelCopyAuthorization</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelCopyAuthorization} obj Optional instance to populate.
   * @return {module:model/ModelCopyAuthorization} The populated <code>ModelCopyAuthorization</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('targetResourceRegion'))
        obj.targetResourceRegion = ApiClient.convertToType(data['targetResourceRegion'], 'String');
      if (data.hasOwnProperty('targetResourceId'))
        obj.targetResourceId = ApiClient.convertToType(data['targetResourceId'], 'String');
      if (data.hasOwnProperty('targetResourceEndpoint'))
        obj.targetResourceEndpoint = ApiClient.convertToType(data['targetResourceEndpoint'], 'String');
      if (data.hasOwnProperty('sourceResourceId'))
        obj.sourceResourceId = ApiClient.convertToType(data['sourceResourceId'], 'String');
      if (data.hasOwnProperty('expirationDateTime'))
        obj.expirationDateTime = ApiClient.convertToType(data['expirationDateTime'], 'Date');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
    }
    return obj;
  }

  /**
   * The region (aka location) of the target speech resource (e.g., westus2).
   * @member {String} targetResourceRegion
   */
  exports.prototype.targetResourceRegion = undefined;

  /**
   * The Azure Resource ID of the target speech resource.
   * @member {String} targetResourceId
   */
  exports.prototype.targetResourceId = undefined;

  /**
   * The endpoint (base url) of the target resource (with custom domain name when it is used).
   * @member {String} targetResourceEndpoint
   */
  exports.prototype.targetResourceEndpoint = undefined;

  /**
   * The Azure Resource ID of the source speech resource.
   * @member {String} sourceResourceId
   */
  exports.prototype.sourceResourceId = undefined;

  /**
   * The expiration date of this copy authorization.
   * @member {Date} expirationDateTime
   */
  exports.prototype.expirationDateTime = undefined;

  /**
   * The ID of this copy authorization.
   * @member {String} id
   */
  exports.prototype.id = undefined;


  return exports;

}));
