/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.OperationResult = factory(root.SpeechServicesApiVersion20241115.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The OperationResult model module.
   * @module model/OperationResult
   * @version 2024-11-15
   */

  /**
   * Constructs a new <code>OperationResult</code>.
   * @alias module:model/OperationResult
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>OperationResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OperationResult} obj Optional instance to populate.
   * @return {module:model/OperationResult} The populated <code>OperationResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('link'))
        obj.link = ApiClient.convertToType(data['link'], 'String');
    }
    return obj;
  }

  /**
   * The link to the result of the operation.
   * @member {String} link
   */
  exports.prototype.link = undefined;


  return exports;

}));
