/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Word'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Word'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.Phrase = factory(root.SpeechServicesApiVersion20241115.ApiClient, root.SpeechServicesApiVersion20241115.Word);
  }
}(this, function(ApiClient, Word) {
  'use strict';

  /**
   * The Phrase model module.
   * @module model/Phrase
   * @version 2024-11-15
   */

  /**
   * Constructs a new <code>Phrase</code>.
   * A transcribed phrase.
   * @alias module:model/Phrase
   * @class
   * @param offsetMilliseconds {Number} The start offset of the phrase in milliseconds.
   * @param durationMilliseconds {Number} The duration of the phrase in milliseconds.
   * @param text {String} The transcribed text of the phrase.
   * @param confidence {Number} The confidence value for the phrase.
   */
  var exports = function(offsetMilliseconds, durationMilliseconds, text, confidence) {
    this.offsetMilliseconds = offsetMilliseconds;
    this.durationMilliseconds = durationMilliseconds;
    this.text = text;
    this.confidence = confidence;
  };

  /**
   * Constructs a <code>Phrase</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Phrase} obj Optional instance to populate.
   * @return {module:model/Phrase} The populated <code>Phrase</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('channel'))
        obj.channel = ApiClient.convertToType(data['channel'], 'Number');
      if (data.hasOwnProperty('speaker'))
        obj.speaker = ApiClient.convertToType(data['speaker'], 'Number');
      if (data.hasOwnProperty('offsetMilliseconds'))
        obj.offsetMilliseconds = ApiClient.convertToType(data['offsetMilliseconds'], 'Number');
      if (data.hasOwnProperty('durationMilliseconds'))
        obj.durationMilliseconds = ApiClient.convertToType(data['durationMilliseconds'], 'Number');
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
      if (data.hasOwnProperty('words'))
        obj.words = ApiClient.convertToType(data['words'], [Word]);
      if (data.hasOwnProperty('locale'))
        obj.locale = ApiClient.convertToType(data['locale'], 'String');
      if (data.hasOwnProperty('confidence'))
        obj.confidence = ApiClient.convertToType(data['confidence'], 'Number');
    }
    return obj;
  }

  /**
   * The 0-based channel index. Only present if channel separation is enabled.
   * @member {Number} channel
   */
  exports.prototype.channel = undefined;

  /**
   * A unique integer number that is assigned to each speaker detected in the audio without particular order. Only present if speaker diarization is enabled.
   * @member {Number} speaker
   */
  exports.prototype.speaker = undefined;

  /**
   * The start offset of the phrase in milliseconds.
   * @member {Number} offsetMilliseconds
   */
  exports.prototype.offsetMilliseconds = undefined;

  /**
   * The duration of the phrase in milliseconds.
   * @member {Number} durationMilliseconds
   */
  exports.prototype.durationMilliseconds = undefined;

  /**
   * The transcribed text of the phrase.
   * @member {String} text
   */
  exports.prototype.text = undefined;

  /**
   * The words that make up the phrase. Only present if word-level timestamps are enabled.
   * @member {Array.<module:model/Word>} words
   */
  exports.prototype.words = undefined;

  /**
   * The locale of the phrase.
   * @member {String} locale
   */
  exports.prototype.locale = undefined;

  /**
   * The confidence value for the phrase.
   * @member {Number} confidence
   */
  exports.prototype.confidence = undefined;


  return exports;

}));
