/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OutputFormatType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OutputFormatType'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.SharedModelFeatures = factory(root.SpeechServicesApiVersion20241115.ApiClient, root.SpeechServicesApiVersion20241115.OutputFormatType);
  }
}(this, function(ApiClient, OutputFormatType) {
  'use strict';

  /**
   * The SharedModelFeatures model module.
   * @module model/SharedModelFeatures
   * @version 2024-11-15
   */

  /**
   * Constructs a new <code>SharedModelFeatures</code>.
   * Features supported by the model.
   * @alias module:model/SharedModelFeatures
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>SharedModelFeatures</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SharedModelFeatures} obj Optional instance to populate.
   * @return {module:model/SharedModelFeatures} The populated <code>SharedModelFeatures</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('supportsTranscriptionsSubmit'))
        obj.supportsTranscriptionsSubmit = ApiClient.convertToType(data['supportsTranscriptionsSubmit'], 'Boolean');
      if (data.hasOwnProperty('supportsTranscriptionsTranscribe'))
        obj.supportsTranscriptionsTranscribe = ApiClient.convertToType(data['supportsTranscriptionsTranscribe'], 'Boolean');
      if (data.hasOwnProperty('supportsEndpoints'))
        obj.supportsEndpoints = ApiClient.convertToType(data['supportsEndpoints'], 'Boolean');
      if (data.hasOwnProperty('supportsTranscriptionsOnSpeechContainers'))
        obj.supportsTranscriptionsOnSpeechContainers = ApiClient.convertToType(data['supportsTranscriptionsOnSpeechContainers'], 'Boolean');
      if (data.hasOwnProperty('supportedOutputFormats'))
        obj.supportedOutputFormats = ApiClient.convertToType(data['supportedOutputFormats'], [OutputFormatType]);
    }
    return obj;
  }

  /**
   * A value indicating whether submission of transcription jobs is supported (POST /transcriptions:submit).
   * @member {Boolean} supportsTranscriptionsSubmit
   */
  exports.prototype.supportsTranscriptionsSubmit = undefined;

  /**
   * A value indicating whether the transcribe action is supported (POST /transcriptions:transcribe).
   * @member {Boolean} supportsTranscriptionsTranscribe
   */
  exports.prototype.supportsTranscriptionsTranscribe = undefined;

  /**
   * A value indicating whether creation of endpoints for live transcription is supported.
   * @member {Boolean} supportsEndpoints
   */
  exports.prototype.supportsEndpoints = undefined;

  /**
   * A value indicating whether this model can be used for transcription on speech container. This feature can be added on existing models when it becomes usable on speech container.
   * @member {Boolean} supportsTranscriptionsOnSpeechContainers
   */
  exports.prototype.supportsTranscriptionsOnSpeechContainers = undefined;

  /**
   * Supported output formats.
   * @member {Array.<module:model/OutputFormatType>} supportedOutputFormats
   */
  exports.prototype.supportedOutputFormats = undefined;


  return exports;

}));
