/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EditsSummary'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EditsSummary'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.TokenErrorDetails = factory(root.SpeechServicesApiVersion20241115.ApiClient, root.SpeechServicesApiVersion20241115.EditsSummary);
  }
}(this, function(ApiClient, EditsSummary) {
  'use strict';

  /**
   * The TokenErrorDetails model module.
   * @module model/TokenErrorDetails
   * @version 2024-11-15
   */

  /**
   * Constructs a new <code>TokenErrorDetails</code>.
   * @alias module:model/TokenErrorDetails
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>TokenErrorDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TokenErrorDetails} obj Optional instance to populate.
   * @return {module:model/TokenErrorDetails} The populated <code>TokenErrorDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('punctuation'))
        obj.punctuation = EditsSummary.constructFromObject(data['punctuation']);
      if (data.hasOwnProperty('capitalization'))
        obj.capitalization = EditsSummary.constructFromObject(data['capitalization']);
      if (data.hasOwnProperty('inverseTextNormalization'))
        obj.inverseTextNormalization = EditsSummary.constructFromObject(data['inverseTextNormalization']);
      if (data.hasOwnProperty('lexical'))
        obj.lexical = EditsSummary.constructFromObject(data['lexical']);
      if (data.hasOwnProperty('others'))
        obj.others = EditsSummary.constructFromObject(data['others']);
    }
    return obj;
  }

  /**
   * @member {module:model/EditsSummary} punctuation
   */
  exports.prototype.punctuation = undefined;

  /**
   * @member {module:model/EditsSummary} capitalization
   */
  exports.prototype.capitalization = undefined;

  /**
   * @member {module:model/EditsSummary} inverseTextNormalization
   */
  exports.prototype.inverseTextNormalization = undefined;

  /**
   * @member {module:model/EditsSummary} lexical
   */
  exports.prototype.lexical = undefined;

  /**
   * @member {module:model/EditsSummary} others
   */
  exports.prototype.others = undefined;


  return exports;

}));
