/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SpeechServicesApiVersion20241115) {
      root.SpeechServicesApiVersion20241115 = {};
    }
    root.SpeechServicesApiVersion20241115.TranscriptionLocales = factory(root.SpeechServicesApiVersion20241115.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The TranscriptionLocales model module.
   * @module model/TranscriptionLocales
   * @version 2024-11-15
   */

  /**
   * Constructs a new <code>TranscriptionLocales</code>.
   * @alias module:model/TranscriptionLocales
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>TranscriptionLocales</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TranscriptionLocales} obj Optional instance to populate.
   * @return {module:model/TranscriptionLocales} The populated <code>TranscriptionLocales</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Transcribe'))
        obj.transcribe = ApiClient.convertToType(data['Transcribe'], ['String']);
      if (data.hasOwnProperty('Submit'))
        obj.submit = ApiClient.convertToType(data['Submit'], ['String']);
    }
    return obj;
  }

  /**
   * @member {Array.<String>} transcribe
   */
  exports.prototype.transcribe = undefined;

  /**
   * @member {Array.<String>} submit
   */
  exports.prototype.submit = undefined;


  return exports;

}));
