/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SpeechServicesApiVersion20241115);
  }
}(this, function(expect, SpeechServicesApiVersion20241115) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CustomModelLinks', function() {
      beforeEach(function() {
        instance = new SpeechServicesApiVersion20241115.CustomModelLinks();
      });

      it('should create an instance of CustomModelLinks', function() {
        // TODO: update the code to test CustomModelLinks
        expect(instance).to.be.a(SpeechServicesApiVersion20241115.CustomModelLinks);
      });

      it('should have the property manifest (base name: "manifest")', function() {
        // TODO: update the code to test the property manifest
        expect(instance).to.have.property('manifest');
        // expect(instance.manifest).to.be(expectedValueLiteral);
      });

      it('should have the property copy (base name: "copy")', function() {
        // TODO: update the code to test the property copy
        expect(instance).to.have.property('copy');
        // expect(instance.copy).to.be(expectedValueLiteral);
      });

      it('should have the property files (base name: "files")', function() {
        // TODO: update the code to test the property files
        expect(instance).to.have.property('files');
        // expect(instance.files).to.be(expectedValueLiteral);
      });

    });
  });

}));
