/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SpeechServicesApiVersion20241115);
  }
}(this, function(expect, SpeechServicesApiVersion20241115) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CustomModelProperties', function() {
      beforeEach(function() {
        instance = new SpeechServicesApiVersion20241115.CustomModelProperties();
      });

      it('should create an instance of CustomModelProperties', function() {
        // TODO: update the code to test CustomModelProperties
        expect(instance).to.be.a(SpeechServicesApiVersion20241115.CustomModelProperties);
      });

      it('should have the property deprecationDates (base name: "deprecationDates")', function() {
        // TODO: update the code to test the property deprecationDates
        expect(instance).to.have.property('deprecationDates');
        // expect(instance.deprecationDates).to.be(expectedValueLiteral);
      });

      it('should have the property customModelWeightPercent (base name: "customModelWeightPercent")', function() {
        // TODO: update the code to test the property customModelWeightPercent
        expect(instance).to.have.property('customModelWeightPercent');
        // expect(instance.customModelWeightPercent).to.be(expectedValueLiteral);
      });

      it('should have the property features (base name: "features")', function() {
        // TODO: update the code to test the property features
        expect(instance).to.have.property('features');
        // expect(instance.features).to.be(expectedValueLiteral);
      });

      it('should have the property error (base name: "error")', function() {
        // TODO: update the code to test the property error
        expect(instance).to.have.property('error');
        // expect(instance.error).to.be(expectedValueLiteral);
      });

    });
  });

}));
