/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SpeechServicesApiVersion20241115);
  }
}(this, function(expect, SpeechServicesApiVersion20241115) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Status', function() {
      beforeEach(function() {
        instance = SpeechServicesApiVersion20241115.Status;
      });

      it('should create an instance of Status', function() {
        // TODO: update the code to test Status
        expect(instance).to.be.a('object');
      });

      it('should have the property notStarted', function() {
        expect(instance).to.have.property('notStarted');
        expect(instance.notStarted).to.be("NotStarted");
      });

      it('should have the property running', function() {
        expect(instance).to.have.property('running');
        expect(instance.running).to.be("Running");
      });

      it('should have the property succeeded', function() {
        expect(instance).to.have.property('succeeded');
        expect(instance.succeeded).to.be("Succeeded");
      });

      it('should have the property failed', function() {
        expect(instance).to.have.property('failed');
        expect(instance.failed).to.be("Failed");
      });

    });
  });

}));
