/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SpeechServicesApiVersion20241115);
  }
}(this, function(expect, SpeechServicesApiVersion20241115) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TextNormalizationKind', function() {
      beforeEach(function() {
        instance = SpeechServicesApiVersion20241115.TextNormalizationKind;
      });

      it('should create an instance of TextNormalizationKind', function() {
        // TODO: update the code to test TextNormalizationKind
        expect(instance).to.be.a('object');
      });

      it('should have the property _default', function() {
        expect(instance).to.have.property('_default');
        expect(instance._default).to.be("Default");
      });

      it('should have the property none', function() {
        expect(instance).to.have.property('none');
        expect(instance.none).to.be("None");
      });

    });
  });

}));
