/*
 * Speech Services API version 2024-11-15
 * Speech Services API version 2024-11-15.
 *
 * OpenAPI spec version: 2024-11-15
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SpeechServicesApiVersion20241115);
  }
}(this, function(expect, SpeechServicesApiVersion20241115) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TranscribeResult', function() {
      beforeEach(function() {
        instance = new SpeechServicesApiVersion20241115.TranscribeResult();
      });

      it('should create an instance of TranscribeResult', function() {
        // TODO: update the code to test TranscribeResult
        expect(instance).to.be.a(SpeechServicesApiVersion20241115.TranscribeResult);
      });

      it('should have the property durationMilliseconds (base name: "durationMilliseconds")', function() {
        // TODO: update the code to test the property durationMilliseconds
        expect(instance).to.have.property('durationMilliseconds');
        // expect(instance.durationMilliseconds).to.be(expectedValueLiteral);
      });

      it('should have the property combinedPhrases (base name: "combinedPhrases")', function() {
        // TODO: update the code to test the property combinedPhrases
        expect(instance).to.have.property('combinedPhrases');
        // expect(instance.combinedPhrases).to.be(expectedValueLiteral);
      });

      it('should have the property phrases (base name: "phrases")', function() {
        // TODO: update the code to test the property phrases
        expect(instance).to.have.property('phrases');
        // expect(instance.phrases).to.be(expectedValueLiteral);
      });

    });
  });

}));
